POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJleHAiOjE3MTE3MzQ4MjcsInVzZXJJZCI6MX0.2slOUjYox-2N4mawkMtzMTdaXNrXR2iNsFqrrYrCpVc

{
    "name": "Brand new Event",
	"description": "Here's a brand new event",
	"location": "Atlanta",
	"datetime": "2024-01-01T15:30:00.000Z"
}
