POST http://localhost:8080/events
content-type: application/json

{
    "name": "Test Event 2",
	"description": "Another Test Event",
	"location": "Atlanta",
	"datetime": "2024-01-01T15:30:00.000Z"
}
