POST http://localhost:8080/events/1/register
authorization: eyJhbGciOJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQG1haWwuY29tIiwiZXhwIjoxNzExNzM0OTM2LCJ1c2VySWQiOjJ9.TKIq4UfkPDLAhzJjK3UKgLH67CQzLr_d0uJnjmYOPW4

